# Generated by Django 4.1.7 on 2023-04-12 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_rename_post_comment_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='recommments', to='blogApp.comment'),
            preserve_default='True',
        ),
    ]
