# Generated by Django 4.1.7 on 2023-04-12 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_comment_parent_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='recomments', to='blogApp.comment'),
        ),
    ]
