# Generated by Django 4.2 on 2023-04-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_rename_deadline_list_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='end_date',
            field=models.DateField(),
        ),
    ]
